// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxfdpfvagaixfsbvgctf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4ZmRwZnZhZ2FpeGZzYnZnY3RmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNzUxODMsImV4cCI6MjA3Mzk1MTE4M30.5UF1_ddSnuB6fXl6S2lZVKpqbiO7uWSwImQiE6Z0WEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});